### PR TITLE
Proposal for new default settings

### PR DESCRIPTION
**Pull request by stefonarch**
Related https://github.com/lxqt/lxqt/discussions/2163
As mentioned, the wallpaper setting  here will override the one from the theme, better choose the same.

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
Wow! I'd mistaken this for changing defaults in the code; should have been tired. GTM, of course.

Please merge it if you don't want to add other keys.

**Comment by stefonarch** [comment]
It's still about first run on fresh vanilla installation, not sure for the default wallpaper and theme yet (clearlooks or light I'd say) - it should fit.

**Comment by tsujan** [comment]
> not sure for the default wallpaper and theme yet 

OK. There's no rush.

And sorry for my mistake. IMO, it's exactly the default conf file that should be changed, instead of the default values in the code.

**Comment by stefonarch** [comment]
IMO "waves-logo.png" is the most suitable choice for the default wallpaper.

**Comment by tsujan** [comment]
I agree with what you see fit.

BTW, why has the automatic check failed? Old branch?

**Comment by stefonarch** [comment]
https://repo.archlinuxcn.org/ è offline, no CI

**Pull request merged**
