### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by stefonarch**
Added the same issue templates, adapted to PcManFm-qt 
https://github.com/stefonarch/pcmanfm-qt/issues/new/choose

### CODE REVIEW

**Comment by tsujan** [comment]
@stefonarch, you may have forgotten to merge this.

**Comment by stefonarch** [comment]
No, waited for a GTM.

**Comment by tsujan** [comment]
It's good everywhere.

**Comment by stefonarch** [comment]
Will have a look which are missing still.

**Pull request merged**
