### PR TITLE
Set required minimum versions

### PR DESCRIPTION
**Pull request by agaida**

### CODE REVIEW

**Comment by tsujan** [comment]
I like this. Sometimes -- as recently -- pcmanfm-qt needs the latest libfm-qt, so it's better to make the dependency always explicit.

**Comment by agaida** [comment]
bah - wrong :D

**Comment by agaida** [comment]
we should take the lib versionion instead of the package version i guess

**Comment by tsujan** [comment]
> we should take the lib versionion instead

OK.

**Pull request merged**
