### PR TITLE
Enable translucency for desktop under Wayland

### PR DESCRIPTION
**Pull request by tsujan**
Closes https://github.com/lxqt/pcmanfm-qt/issues/1949

### CODE REVIEW

**Review by kRHYME7 — APPROVED** [review]
Werks

**Review by stefonarch — APPROVED** [review]
Works fine. 
Why didn't you use  the  `setAttribute(Qt::WA_TranslucentBackground);`?
And why only  Wayland?

**Comment by tsujan** [comment]
> Why didn't you use the setAttribute(Qt::WA_TranslucentBackground);?

I did ;) Only under Wayland.

> And why only Wayland?

Because window translucency makes sense only with compositing, and X11 can be without compositing.

**Comment by stefonarch** [comment]
> I did ;) Only under Wayland.

I need new glasses or should were them ;)

**Pull request merged**
