### PR TITLE
Initial Travis CI setup

### PR DESCRIPTION
**Pull request by yan12125**

### CODE REVIEW

**Comment by tsujan** [comment]
@yan12125 
Feel free to merge it if your work is complete. I know nothing about Travis.

**Comment by yan12125** [comment]
Not sure if I missed some steps...

**Comment by yan12125** [comment]
OK it works, just that the build started 20 minutes after I pushed it. Maybe GitHub or Travis CI is too busy.

**Comment by tsujan** [comment]
> Maybe GitHub or Travis CI is too busy.

I encountered problems with GitHub in the last 2-3 days. They appeared and disappeared.

**Comment by yan12125** [comment]
> the last 2-3 days

That reminds me of https://www.githubstatus.com/, and yes - several GitHub services suffered from degraded performance yesterday :/

**Pull request merged**
