### PR TITLE
Desktop Prefs: Change no wallpaper option to groupbox checkbox

### PR DESCRIPTION
**Pull request by isf63**
Change the _Wallpaper mode_ combobox option "Fill with background color only" to a wallpaper groupbox checkbox.

### CODE REVIEW

**Comment by tsujan** [comment]
While appreciating your work, I see no reason for this change. The GUI is clear enough; adding a checbox doesn't make it clearer.

**Comment by isf63** [comment]
On further inspection, `DesktopPreferencesDialog::onWallpaperModeChanged` could be simplified with this change (as a groupbox checkbox's default behavior is to disable the contents when unchecked.)

I think it does simplify the UI, but that's only my opinion. If the UI isn't clear enough a tooltip to the groupbox label could be added. If and only if this is a desirable, further changes should be made due to potential errors.

**Comment by tsujan** [comment]
> I think it does simplify the UI

I'm afraid an extra box to check is the opposite of simplification.

**Comment by isf63** [comment]
Okay, closing the PR. Also I accidentally overwrote a previous PR with this one, which I'll reopen.

**Comment by tsujan** [comment]
> Also I accidentally overwrote a previous PR with this one, which I'll reopen

Yes, please reopen it. I saw it and wanted to review it when I found the time.

**Pull request closed without merging**
