### PR TITLE
Migrate to the new libfm-qt Fm::FileLauncher API.

### PR DESCRIPTION
**Pull request by PCMan**
This needs https://github.com/lxqt/libfm-qt/pull/186

### CODE REVIEW

**Comment by tsujan** [comment]
@agaida I see them as an annoyance ;)

**Comment by tsujan** [comment]
I don't want to start a discussion about this new trend -- I just dislike it -- but, for example, that "falls through blah blah" message made me do a wrong thing in libfm-qt PR 186 today. I realized that when searching for the cause of a real problem, in contrast to false problems some of these warnings create. Whether I'm stupid or these new warnings is another question ;)

**Comment by tsujan** [comment]
"BTW", found a real problem to fix here: the quick execution option isn't respected.

**Comment by agaida** [comment]
btw: some annoyances quickly mutate to real bugs - esp. when maintainers switch warnings to bugs in the compiler preset - and yes, i know exactly what i'm talking about. Bitten by debians presettings more than one time - do you remember the g_assert bug in libfm?

**Comment by tsujan** [comment]
I don't deny the fact that some of them are not only useful but necessary. However, even things like usefulness or happiness have a limit, beyond which they would be senseless :D

**Comment by agaida** [comment]
GTM

**Pull request merged**
