### PR TITLE
Add Escape as a shortcut to dismiss filter

### PR DESCRIPTION
**Pull request by manaskarekar**
Add Escape as a shortcut to dismiss filter, subject to discussion in #945.

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks a lot! It looks good. Will review and test it soon.

**Comment by tsujan** [comment]
@manaskarekar You didn't need to close it.

**Comment by manaskarekar** [comment]
Oops, that was unintentional.

**Comment by tsujan** [comment]
For your future contributions:

You could add "fixes put_issue_address_here" or "closes put_issue_address_here" to your PR's main comment for the corresponding issue to be closed automatically after your PR is merged.

**Pull request merged**
