### PR TITLE
Update string to reflect smooth scroll setting

### PR DESCRIPTION
**Pull request by galaxyhaxz**
Depends on: https://github.com/lxqt/libfm-qt/pull/802

Update string to reflect change. Some of the translations will have to be updated, but most of them said "unfinished" anyway...

### CODE REVIEW

**Comment by tsujan** [comment]
→ https://github.com/lxqt/libfm-qt/pull/802#issuecomment-1109398086

Also, in your future contributions, please don't change translation files.

**Comment by galaxyhaxz** [comment]
> Also, in your future contributions, please don't change translation files.

Then how are you supposed to do it?

**Comment by galaxyhaxz** [comment]
> Also, in your future contributions

I won't even bother making future contributions if you don't even bother accepting them...

**Comment by tsujan** [comment]
> Then how are you supposed to do it?

It will done by @stefonarch. Code contributors shouldn't touch translations.

> I won't even bother making future contributions if you don't even bother accepting them...

PRs may be accepted or rejected, of course.

**Comment by galaxyhaxz** [comment]
> Code contributors shouldn't touch translations.

Fair enough. I made the assumption it would break compiling as the compiler would have to lookup all strings and build a binary version of them.

**Pull request closed without merging**
