### PR TITLE
Added "invert selection" shortcut

### PR DESCRIPTION
**Pull request by stefonarch**
There is no easy way to unselect after ctrl+A using the  keyboard, I was missing that.
ctrl+shift+a inverts selection.
Could be also another instead of this one.

### CODE REVIEW

**Comment by tsujan** [comment]
GTM

**Comment by tsujan** [comment]
> Could be also another instead of this one.

It's usually `Ctrl+I` but it's used by the filter bar (and that was the reason why "Invert Selection" had no shortcut) but `Ctrl+Shift+A` is acceptable.

**Comment by stefonarch** [comment]
I see that on the desktop this has no effect (ctrl+A is working). But no big thing.

**Comment by tsujan** [comment]
Menu shortcuts are for windows. Desktop defines its own shortcuts in its code and no, it has no shortcut for selection inversion.

**Pull request merged**
