### PR TITLE
Fixed the links of About dialog

### PR DESCRIPTION
**Pull request by tsujan**
I didn't find the commit that had created the problem, but the wiki link had replaced the site link.

### CODE REVIEW

**Comment by tsujan** [comment]
about

**Comment by stefonarch** [comment]
Here the link isn't even working.
I found https://github.com/lxqt/pcmanfm-qt/commit/6ce631228d4f12ac5411766468ba8448bc579809 but it's not about the wiki.

**Comment by stefonarch** [comment]
Btw you could add yourself to "author" ;)

**Comment by tsujan** [comment]
> Here the link isn't even working.

Yes, the PR also fixes that.

The only change I'd made was https://github.com/lxqt/pcmanfm-qt/commit/6ce631228d4f12ac5411766468ba8448bc579809, which was only about the removal of hard-coded colors. Could a translation PR have created the issue?

> Btw you could add yourself to "author" ;)

I think it's better to keep that page for the original author, but maybe later.

**Comment by tsujan** [comment]
It rather seems that I (or someone else?) wanted to add the wiki link but was distracted by another code.

Anyway, it's simple. Merging...

**Comment by stefonarch** [comment]
> It rather seems that I (or someone else?) wanted to add the wiki link but was distracted by another code.

Thinking about it I'm afraid that it was me, some months ago I had this idea and made a test but didn't like it much.

**Comment by stefonarch** [comment]
It sneaked in here https://github.com/lxqt/pcmanfm-qt/commit/2ab2d4a387200f2a09ab316575d85525ecd80c39
The update script uses` git stash && git pull ` but apparently it missed that test somehow.

**Comment by tsujan** [comment]
It's OK. These things happen. It could have easily been me ;)

**Pull request merged**
