### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by tsujan**
IMHO, this needs to be done for all LXQt apps once in a while.

### CODE REVIEW

**Comment by TarasPanchenko** [comment]
Dear PCMan,

when I check translations of PCManFM-qt I was found double usage "p" letter in "View" menu:

S&plit View
&Preserve Settings for This Folder

Please, check

--
WBR, Taras

**Comment by stefonarch** [comment]
Not sure if that is an big issue, hitting P twice will do, and translators often chose randomly the character to assign.

**Comment by TarasPanchenko** [comment]
"hitting twice" not working for me (void linux)

**Comment by stefonarch** [comment]
I checked now, and in git and upcoming versions it's in submenu, so hitting C and _then_ hitting P is needed to activate it.
schermata-09-13-15-43

**Comment by tsujan** [comment]
For working with accelerators, `Alt` should be kept pressed with some widget styles (like Breeze and Kvantum). If you don't see an underline anywhere, you're using a widget style that hides accelerators without `Alt`.

**Comment by TarasPanchenko** [comment]
ok, thanks, with pressed Alt twice P working good.
version 0.17.0

**Comment by tsujan** [comment]
Oh, sorry, I may have misunderstood your comment.

As @stefonarch mentioned, "Preserve Settings for This Folder" has been removed from git. Instead, "Customized View Settings" has been added (it doesn't have "P").

However, "Customized View Settings" doesn't have an accelerator (with or without `Alt`).

@stefonarch, in your screenshot, "C" is underlined. That's strange because its text doesn't include an underline in `main-win.ui`. Am I mistaken? Does Fusion add it automatically?

**Comment by tsujan** [comment]
I made https://github.com/lxqt/pcmanfm-qt/pull/1445

**Comment by stefonarch** [comment]
Widget style is qtcurve, and I see an accelerator also in italian, but you're right, there is none:
https://translate.lxqt-project.org/translate/lxqt-desktop/pcmanfm-qt/it/?checksum=321beca1f6ddafd2&q=customized&sort_by=-priority%2Cposition
schermata-09-13-20-04


> I made #1445
This will probably remove all existing translations (and hopefully not generate another merge conflict). But it's ok for me to try it out.

**Comment by tsujan** [comment]
> This will probably remove all existing translations

Yes, as I mentioned in PR's comment. That's why I didn't merge it myself.

**Comment by stefonarch** [comment]
I saw the PR comment afterwards. Anyway, committing in weblate and merging pending translations resulted in another rebase issue atm.

**Pull request merged**
