### PR TITLE
Changing a mistyped word

### PR DESCRIPTION
**Pull request by shga89**
I had typed "이동(*G)" instead of "이동(&G)", so I changed it.

### CODE REVIEW

**Comment by yan12125** [comment]
This commit appears to break building

```
lrelease error: Parse error at /build/pcmanfm-qt-git/src/pcmanfm-qt/pcmanfm/translations/pcmanfm-qt_ko.ts:1265:27: Expected ';', but got ')'.
```

Full build log can be found at https://build.archlinuxcn.org/~imlonghao/log/pcmanfm-qt-git/2020-07-08T17:17:02.html

**Comment by tsujan** [comment]
@yan12125 

Thank you so much! I never thought that a translation could break compilation!

**Comment by tsujan** [comment]
I reverted it.

**Comment by yan12125** [comment]
@tsujan Thanks! 

@shga89 could you create another PR to properly fix it?

**Comment by tsujan** [comment]
@yan12125 
I learned my lesson: every time I want to merge a translation, I should open it with Qt Linguist.

**Comment by shga89** [comment]
#1155 
@tsujan @yan12125 
I uploaded the modified file.

Sorry for the confusion of you.

**Pull request merged**
