### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/lxqt-desktop/pcmanfm-qt/) for LXQt Desktop/PCManFm-qt.

### CODE REVIEW

**Comment by stefonarch** [comment]
@tsujan  @yan12125 here again this replacement of the special characters, I contacted the author last time and he said he didn't edit them.
I checked the history now in weblate and only the "recent files" entries were modified be him. So it looks like weblate does that automatically.

**Comment by tsujan** [comment]
If `lxqt-transupdate` does it too (I think it does), consider it correct.

**Comment by stefonarch** [comment]
It does it, but it looks like at the first french commit in weblate they are removed. There is check in weblate https://docs.weblate.org/en/latest/user/checks.html#punctuation-spacing but clicking "fix string" it it inserts a normal space . and it's  not automatic AFAIK, but I've to recheck.
schermata-11-29-13-56

**Comment by yan12125** [comment]
Googling "French colon nbsp", it seems the space before some punctuations should be a non-breaking space (0xA0) instead of a normal one (0x20). If a French speaker can confirm this, it's better to add those non-breaking spaces back and report bugs to qttools and/or weblate IMO.

**Comment by stefonarch** [comment]
This is clear, I don't understand what weblate does, I made a test and reinserted `&#xa0;` in one translation, but I saw that the result was worse:
schermata-12-01-07-53

schermata-12-01-07-52

I think the only way is to run a final `lupdate` just before releasing. Probably it's very rare that happens a line break just there; something like

```
text text keep in mind
: this is important
```

**Pull request merged**
